apiVersion: apps/v1
kind: Deployment
metadata:
  name: capstone-rolling-update
  labels: 
    app: capstone-html-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: simple-html-app
  template:
    metadata:
      labels:
        app: simple-html-app
        role: rolling-update
    spec:
      containers:
      - name: simple-html-container
        image: sarastavaski/simple-index:v3
        imagePullPolicy: "Always"
        ports:
        - containerPort: 80
        readinessProbe:
          httpGet:
            path: /
            port: 80
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 1
